version: "3.8"

# run
# docker-compose up -d

# $ wget http://localhost:3000/
# ps> Invoke-WebRequest http://localhost:3000/

# stop
# docker-compose down

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html