version: "3.8"

# run with rebuild
# docker-compose up -d --build

# run
# docker-compose up -d

# $ wget http://localhost:3000/
# ps> Invoke-WebRequest http://localhost:3000/

# stop
# docker-compose down

# stop and remove volumes
# docker-compose down -v

# config file
# docker cp frontend-web:/etc/apache2/apache2.conf configs/
# docker cp frontend-web:/usr/local/etc/php/php.ini-production configs/
# docker cp backend-db:/etc/mysql/my.cnf configs/

# check timezone for php
# 1. enter container
#   $ docker exec -it frontend-web bash
# 2. check system config and date
#   $ echo $TZ
#   $ date
# 3. php config
#   $ php --info | grep timezone
# 4. php source code
#   <? echo date("Y-m-d h:i:s") ?>

# check timezone for mariadb
# 1. enter container
#   $ docker exec -it backend-db bash
# 2. check system config and date
#   $ echo $TZ
#   $ date
# 3. login DB to check the timezone
#   mysql -u root mysql -p
#   > select @@global.time_zone, @@session.time_zone;
#   it will show 'system' or the timezone you set

# docker exec -it frontend-web bash
# docker exec -it backend-db bash

# docker logs frontend-web
# docker logs backend-db

# docker network inspect my-bus

# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' backend-db
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' frontend-web

services:
  php:
    container_name: frontend-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html
      - ./configs/php.ini-production:/usr/local/etc/php/php.ini:ro
      - ./configs/apache2.conf:/etc/apache2/apache2.conf:ro
    depends_on:
      - mariadb
    networks:
      - backbone
    environment:
      DB_HOST: backend-db
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  mariadb:
    container_name: backend-db
    image: mariadb:10.3
    ports:
      - 3306:3306
    networks:
      - backbone
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Taipei
    volumes:
      - dbvolume:/var/lib/mysql
      - ./configs/my.cnf:/etc/mysql/my.cnf:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  dbvolume:

networks:
  backbone:
    name: my-bus